### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FriendlyAI** [ApolloZhu/HooHacks-2019#1]
- [ ] Leave mark on top of houses clicked with their prices perspectively, if available
- [ ] Integrate Google Cloud Platform (Maybe cloud anchor? then the session data need to be transferred)
- [ ] Integrate MicroStrategy (Tedious work to do there, but could be very helpful)
- [ ] Adjust map FOV, orientation, and tilt based on device censors
- [ ] Finalize app name
- [ ] Finalize app icon

**Comment by ApolloZhu** [comment]
Forgotten

```xml
<localRealEstate>
    <region id="271856" type="neighborhood" name="East Queen Anne">
```

House Information

```swift
/// The year in which the property was constructed.
let yearBuilt: Int // yearBuilt

/// The size of the lot in sq. ft.
let lotSize: Int // lotSizeSqFt
/// The size of the finished property in sq. ft.
let propertySize: Int // finishedSqFt

/// Number of bathrooms in the property.
let bathroomsCount: Double // bathrooms
/// Number of bedrooms in the property.
let bedroomsCount: Int // bedrooms

/// The year of the most recent tax assessment
let taxAssessmentYear: Int // taxAssessmentYear
/// The most recent tax assessment
let taxAssessment: Int // taxAssessment

/// The date of last sale for this property.
let lastSoldDate: String // lastSoldDate, MM/dd/yyyy
/// The price of the last sale for this property.
let lastSoldPrice: Int // lastSoldPrice
```
